export enum CountryCode {
  Australia = 'au',
  Austria = 'at',
  Belgium = 'be',
  Brazil = 'br',
  Bulgaria = 'bg',
  Canada = 'ca',
  China = 'cn',
  Croatia = 'hr',
  CzechRepublic = 'cz',
  Denmark = 'dk',
  Finland = 'fi',
  France = 'fr',
  Germany = 'de',
  Hungary = 'hu',
  India = 'in',
  Israel = 'il',
  Italy = 'it',
  Japan = 'jp',
  Mexico = 'mx',
  Netherlands = 'nl',
  Newzealand = 'nz',
  Nigeria = 'ng',
  Norway = 'no',
  Poland = 'pl',
  Portugal = 'pt',
  Spain = 'es',
  Turkey = 'tr',
  Ukraine = 'ua',
  UnitedKingdom = 'gb',
  UnitedStates = 'us',
}

export enum Category {
  Business = 'business',
  Entertainment = 'entertainment',
  General = 'general',
  Health = 'health',
  Science = 'science',
  Sports = 'sports',
  Technology = 'technology',
}
